incoming_balance = ""
incoming_balance_index = ""
incoming_balance_merkle_proof = ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""]
incoming_balance_root = ""
nullifier_key = ""
nullifier_value = ""
prev_nonce = ""
prev_shadow_balance = ""
prev_shadow_balance_index = ""
prev_shadow_balance_merkle_proof = ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""]
prev_shadow_balance_root = ""
recipient_account = ""
secret = ""
sender_account = ""
transfer_amount = ""
