[package]
name = "relayer"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy = "0.11.1"
anyhow = "1.0.96"
dotenv = "0.15.0"
rocket = { version = "0.5.1", features = ["json"] }
serde = "1.0.218"
tokio = { version = "1.43.0", features = ["rt-multi-thread"] }
